name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install project (runtime deps)
      run: |
        pip install build
        pip install .

    - name: Install dev tools
      run: pip install pytest

    - name: Run test-suite
      run: pytest
