name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # ── Check out source ─────────────────────────────────────────────────
    - name: Check out source
      uses: actions/checkout@v4

    # ── Python toolchain ────────────────────────────────────────────────
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # ── Install runtime *and* dev deps (pytest, ruff, locust, …) ────────
    - name: Install project (+ dev extras)
      run: |
        pip install build
        pip install .[dev]

    # ── Run the unit-test suite ─────────────────────────────────────────
    - name: Run pytest
      run: pytest

    # ── Start the API so Locust can hit it ──────────────────────────────
    - name: Launch API server
      run: |
        uvicorn gdpr_engine.api:app --port 8000 --log-level warning &
        echo $! > uvicorn.pid
        sleep 3                 # give FastAPI + SQLite a moment to start

    # ── Quick smoke-test with 10 users for 10 s ─────────────────────────
    - name: Locust smoke-test (10 users · 10 s)
      run: |
        locust -f locustfile.py \
               --headless -u 10 -r 10 -t 10s \
               --host http://localhost:8000 \
               --exit-code-on-error 0      # do NOT fail the job on 4xx/5xx

    # ── Always stop the background server ──────────────────────────────
    - name: Stop API server
      if: always()
      run: kill "$(cat uvicorn.pid)"
